import { createBrowserRouter } from "react-router-dom";
import Root from "./pages/Root";
import ErrorPage from "./pages/ErrorPage/ErrorPage";
import Auth from "./pages/Auth";
import Request from "./pages/Request";
import React from "react";
import Schedule from "./pages/Schedule";
import Statistics from "./pages/Statistics";
import { loadWork } from "./http/emiasAPI";

// let requests = [
//   {
//     EvnClass_id: "27",
//     Diag_FullName: "T07. Множественные травмы неуточненные",
//     EvnDirection_id: "500801239434245",
//     EvnDirection_IsConcilium: "1",
//     EvnDirection_pid: "500801238930404",
//     EvnDirection_rid: "500801238930388",
//     RootEvnClass_SysNick: "EvnPS",
//     EvnUslugaTelemed_id: "500801239504243",
//     ConsultingForm_Name: "Онлайн",
//     Diag_id: "11702",
//     Person_id: "500801003356077",
//     PersonEvn_id: "500801042789862",
//     Server_id: "13101072",
//     EvnDirection_Num: "952412",
//     PayType_id: "201",
//     EvnDirection_setDT: "08.09.2023",
//     EvnDirection_insDate: "08.09.2023",
//     EvnDirection_insTime: "13:51",
//     Lpu_Nick: 'ГБУЗ МО "ВРКБ"',
//     Lpu_id: "13100903",
//     RiskType_id: null,
//     Person_Fin: "МОНГУШ АА",
//     MedPersonalFIO_whom_sent: null,
//     Person_FIO: "СЕЛЬМАНОВИЧ АЛЕКСАНДР ЛЕОНИДОВИЧ",
//     EvnDirection_IsCito: "false",
//     RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
//     LpuSectionProfile_Name: "анестезиологии и реаниматологии",
//     UslugaTelemedResultType_Name:
//       "Подтверждение диагноза без коррекции лечения",
//     ConsultationForm_Code: "3",
//     ConsultationForm_Name: "Экстренная",
//     isDel: "1",
//     evndirection_faildt_fororder: null,
//     evnuslugatelemed_id_fororder: "500801239504243",
//     evndirection_iscito_fororder: "1",
//     evndirection_setdt_fororder: "2023-09-08 00:00:00",
//     deadLine: "08.09.2023 15:51",
//     deadDiff: "44",
//     DirType_Code: "13",
//     EvnQueue_id: "500801239434244",
//     TimeTableStac_id: null,
//     TimeTableGraf_id: null,
//     TimeTableMedService_id: null,
//     EvnStatusCause_Name: null,
//     evndirection_result: "Подтверждение диагноза без коррекции лечения",
//     EvnXml_id: null,
//     EvnXml_IsSigned: null,
//     EvnXml_signDT: null,
//     pmUser_signName: null,
//     RequestConsult_id: "2",
//     EvnConcilium_id: null,
//     ConciliumType_id: null,
//     MedService_id: "11380",
//     Org_tid: "13101155",
//     RemoteConsultCause_id: "2",
//     RecMethodType_id: "10",
//     EvnDirection_isAuto: "1",
//     Evn_IsSigned: null,
//     Evn_signDT: null,
//     EvnConciliumStatus_SysNick: null,
//     EvnDirectionStatus_SysNick: "Serviced",
//     isConciliumMember: "1",
//     ConciliumResults_id: null,
//     pmUser_insID: "363459999167",
//     UslugaComplex_did: null,
//     evndirection_group: "4",
//     TimeTable_begTime: null,
//     ConsultingForm_id: "2",
//   },
//   {
//     EvnClass_id: "27",
//     Diag_FullName: "I25.2. Перенесенный в прошлом инфаркт миокарда",
//     EvnDirection_id: "500801239307323",
//     EvnDirection_IsConcilium: "1",
//     EvnDirection_pid: "500801236737140",
//     EvnDirection_rid: "500801236732167",
//     RootEvnClass_SysNick: "EvnPS",
//     EvnUslugaTelemed_id: null,
//     ConsultingForm_Name: "Офлайн",
//     Diag_id: "5419",
//     Person_id: "2715869",
//     PersonEvn_id: "500801043006306",
//     Server_id: "13101283",
//     EvnDirection_Num: "2014146",
//     PayType_id: "201",
//     EvnDirection_setDT: "08.09.2023",
//     EvnDirection_insDate: "08.09.2023",
//     EvnDirection_insTime: "11:56",
//     Lpu_Nick: 'ГБУЗ МО "ЛЮБЕРЕЦКАЯ ОБ"',
//     Lpu_id: "13101283",
//     RiskType_id: null,
//     Person_Fin: "ПАРШИКОВА ЕН",
//     MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
//     Person_FIO: "ОБУХОВ АЛЕКСАНДР ЮРЬЕВИЧ",
//     EvnDirection_IsCito: "false",
//     RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
//     LpuSectionProfile_Name: "сердечно-сосудистой хирургии",
//     UslugaTelemedResultType_Name: null,
//     ConsultationForm_Code: "2",
//     ConsultationForm_Name: "Неотложная",
//     isDel: "1",
//     evndirection_faildt_fororder: null,
//     evnuslugatelemed_id_fororder: null,
//     evndirection_iscito_fororder: "1",
//     evndirection_setdt_fororder: "2023-09-08 00:00:00",
//     deadLine: "09.09.2023 11:56",
//     deadDiff: "18",
//     DirType_Code: "13",
//     EvnQueue_id: "500801239307322",
//     TimeTableStac_id: null,
//     TimeTableGraf_id: null,
//     TimeTableMedService_id: null,
//     EvnStatusCause_Name: null,
//     evndirection_result: null,
//     EvnXml_id: null,
//     EvnXml_IsSigned: null,
//     EvnXml_signDT: null,
//     pmUser_signName: null,
//     RequestConsult_id: "2",
//     EvnConcilium_id: null,
//     ConciliumType_id: null,
//     MedService_id: "11380",
//     Org_tid: "13101155",
//     RemoteConsultCause_id: "2",
//     RecMethodType_id: "10",
//     EvnDirection_isAuto: "1",
//     Evn_IsSigned: null,
//     Evn_signDT: null,
//     EvnConciliumStatus_SysNick: null,
//     EvnDirectionStatus_SysNick: "Queued",
//     isConciliumMember: "1",
//     ConciliumResults_id: null,
//     pmUser_insID: "347280479071",
//     UslugaComplex_did: null,
//     evndirection_group: "3",
//     TimeTable_begTime: null,
//     ConsultingForm_id: "1",
//   },
//   {
//     EvnClass_id: "27",
//     Diag_FullName:
//       "I80.0. Флебит и тромбофлебит поверхностных сосудов нижних конечностей",
//     EvnDirection_id: "500801239397791",
//     EvnDirection_IsConcilium: "1",
//     EvnDirection_pid: "500801235688423",
//     EvnDirection_rid: "500801235688407",
//     RootEvnClass_SysNick: "EvnPS",
//     EvnUslugaTelemed_id: null,
//     ConsultingForm_Name: "Офлайн",
//     Diag_id: "5661",
//     Person_id: "500801003357917",
//     PersonEvn_id: "500801042827632",
//     Server_id: "13101156",
//     EvnDirection_Num: "762907",
//     PayType_id: "201",
//     EvnDirection_setDT: "08.09.2023",
//     EvnDirection_insDate: "08.09.2023",
//     EvnDirection_insTime: "13:14",
//     Lpu_Nick: "ГБУЗ МО «СОКБ»",
//     Lpu_id: "13101156",
//     RiskType_id: null,
//     Person_Fin: "ГОЛОВИН ВВ",
//     MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
//     Person_FIO: "ГУЛЯЕВ ЕВГЕНИЙ АЛЕКСАНДРОВИЧ",
//     EvnDirection_IsCito: "true",
//     RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
//     LpuSectionProfile_Name: "нефрологии",
//     UslugaTelemedResultType_Name: null,
//     ConsultationForm_Code: "3",
//     ConsultationForm_Name: "Экстренная",
//     isDel: "1",
//     evndirection_faildt_fororder: null,
//     evnuslugatelemed_id_fororder: null,
//     evndirection_iscito_fororder: "2",
//     evndirection_setdt_fororder: "2023-09-08 00:00:00",
//     deadLine: "08.09.2023 15:14",
//     deadDiff: "44",
//     DirType_Code: "13",
//     EvnQueue_id: "500801239397790",
//     TimeTableStac_id: null,
//     TimeTableGraf_id: null,
//     TimeTableMedService_id: null,
//     EvnStatusCause_Name: null,
//     evndirection_result: null,
//     EvnXml_id: null,
//     EvnXml_IsSigned: null,
//     EvnXml_signDT: null,
//     pmUser_signName: null,
//     RequestConsult_id: "2",
//     EvnConcilium_id: null,
//     ConciliumType_id: null,
//     MedService_id: "11380",
//     Org_tid: "13101155",
//     RemoteConsultCause_id: "2",
//     RecMethodType_id: "10",
//     EvnDirection_isAuto: "1",
//     Evn_IsSigned: null,
//     Evn_signDT: null,
//     EvnConciliumStatus_SysNick: null,
//     EvnDirectionStatus_SysNick: "Queued",
//     isConciliumMember: "1",
//     ConciliumResults_id: null,
//     pmUser_insID: "419862796350",
//     UslugaComplex_did: null,
//     evndirection_group: "3",
//     TimeTable_begTime: null,
//     ConsultingForm_id: "1",
//   },
// ];
let requests = loadWork();

export const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    errorElement: <ErrorPage />,
    children: [
      {
        path: "login",
        element: <Auth />,
      },
      {
        path: "request",
        element: <Request requests={requests} />,
      },
      {
        path: "schedule",
        element: <Schedule />,
      },
      {
        path: "report",
        element: <Statistics />,
      },
    ],
  },
]);
