import React, { useContext } from "react";
import { Card, Nav, Row } from "react-bootstrap";
import { Context } from "../../index";
import { observer } from "mobx-react-lite";
import PatientCard from "./PatientCard";
import { combineOnlySpecialties, sortRequests } from "../../utils/functions";

const requests = [
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801238498941",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801237995372",
    EvnDirection_rid: "500801237955015",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801238997071",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "3983387",
    PersonEvn_id: "500801043233861",
    Server_id: "13101027",
    EvnDirection_Num: "847818",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "11:34",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "СОЛЕНОВА ВЕРА МИХАЙЛОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801238997071",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "08.09.2023 11:34",
    deadDiff: "5",
    DirType_Code: "13",
    EvnQueue_id: "500801238498940",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801238483602",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238133682",
    EvnDirection_rid: "500801238126295",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801238996553",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "500801002104543",
    PersonEvn_id: "500801043263205",
    Server_id: "13101027",
    EvnDirection_Num: "847748",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "11:23",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "Еремин Василий Степанович",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801238996553",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "08.09.2023 11:23",
    deadDiff: "5",
    DirType_Code: "13",
    EvnQueue_id: "500801238483601",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
    EvnDirection_id: "500801238704781",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238634033",
    EvnDirection_rid: "500801238580826",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801238998112",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5577",
    Person_id: "500801003380785",
    PersonEvn_id: "500801043349985",
    Server_id: "13101027",
    EvnDirection_Num: "849009",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "14:15",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "КРАУСОВА АЛЕКСАНДРА АЛЕКСЕЕВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801238998112",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "08.09.2023 14:15",
    deadDiff: "2",
    DirType_Code: "13",
    EvnQueue_id: "500801238704779",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801238742006",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238667698",
    EvnDirection_rid: "500801238605995",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801238999079",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "5463106",
    PersonEvn_id: "500801043354958",
    Server_id: "13101027",
    EvnDirection_Num: "849222",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "14:46",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "ВЕКШИНА НАДЕЖДА ВАСИЛЬЕВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "1",
    ConsultationForm_Name: "Плановая",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801238999079",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "21.09.2023 14:46",
    deadDiff: "309",
    DirType_Code: "13",
    EvnQueue_id: "500801238742005",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "E10.7. Инсулинзависимый сахарный диабет с множественными осложнениями",
    EvnDirection_id: "500801238989132",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801232666344",
    EvnDirection_rid: "500801232666333",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "3978",
    Person_id: "3048049",
    PersonEvn_id: "44100598",
    Server_id: "0",
    EvnDirection_Num: "523252",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "23:38",
    Lpu_Nick: 'ГБУЗ МО "КОЛОМЕНСКАЯ ОБЛАСТНАЯ БОЛЬНИЦА"',
    Lpu_id: "500801000000014",
    RiskType_id: null,
    Person_Fin: "ЕРМИЛОВ ВЮ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "КРЮЧКОВА МАРИЯ СЕРГЕЕВНА",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Другое",
    LpuSectionProfile_Name: "пульмонологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "08.09.2023 01:38",
    deadDiff: "30",
    DirType_Code: "13",
    EvnQueue_id: "500801238989131",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "4",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "348425304652",
    UslugaComplex_did: null,
    evndirection_group: "2",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "K73.9. Хронический гепатит неуточненный",
    EvnDirection_id: "500801238577383",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801234538042",
    EvnDirection_rid: "500801234204801",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801238996864",
    ConsultingForm_Name: "Онлайн",
    Diag_id: "6257",
    Person_id: "1655556",
    PersonEvn_id: "500801032071797",
    Server_id: "500801000000004",
    EvnDirection_Num: "1058693",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "12:34",
    Lpu_Nick: 'ГБУЗ МО "Орехово-Зуевская областная больница"',
    Lpu_id: "500801000000004",
    RiskType_id: null,
    Person_Fin: "Якоева ЕВ",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ИОНОВА НАТАЛИЯ ВЛАДИМИРОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "инфекционным болезням",
    UslugaTelemedResultType_Name: "Подтверждение диагноза с коррекцией лечения",
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801238996864",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "07.09.2023 14:34",
    deadDiff: "19",
    DirType_Code: "13",
    EvnQueue_id: "500801238577382",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза с коррекцией лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "345912332661",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "2",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "E10.7. Инсулинзависимый сахарный диабет с множественными осложнениями",
    EvnDirection_id: "500801238989320",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801232666344",
    EvnDirection_rid: "500801232666333",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239066872",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "3978",
    Person_id: "3048049",
    PersonEvn_id: "44100598",
    Server_id: "0",
    EvnDirection_Num: "523254",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "23:41",
    Lpu_Nick: 'ГБУЗ МО "КОЛОМЕНСКАЯ ОБЛАСТНАЯ БОЛЬНИЦА"',
    Lpu_id: "500801000000014",
    RiskType_id: null,
    Person_Fin: "ЕРМИЛОВ ВЮ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "КРЮЧКОВА МАРИЯ СЕРГЕЕВНА",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Другое",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name: "Подтверждение диагноза с коррекцией лечения",
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239066872",
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "08.09.2023 01:41",
    deadDiff: "30",
    DirType_Code: "13",
    EvnQueue_id: "500801238989319",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза с коррекцией лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "4",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "348425304652",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I67.2. Церебральный атеросклероз",
    EvnDirection_id: "500801238985675",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238876980",
    EvnDirection_rid: "500801238849153",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239062173",
    ConsultingForm_Name: "Онлайн-чат",
    Diag_id: "5593",
    Person_id: "500801003137042",
    PersonEvn_id: "500801043399134",
    Server_id: "13101027",
    EvnDirection_Num: "850576",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "23:13",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕТИНА ДВ",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "Матвейчук Зинаида Александровна",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239062173",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "08.09.2023 23:13",
    deadDiff: "6",
    DirType_Code: "13",
    EvnQueue_id: "500801238985674",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "1",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "370866297654",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "3",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "K73.9. Хронический гепатит неуточненный",
    EvnDirection_id: "500801238572230",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801234538042",
    EvnDirection_rid: "500801234204801",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239037797",
    ConsultingForm_Name: "Онлайн",
    Diag_id: "6257",
    Person_id: "1655556",
    PersonEvn_id: "500801032071797",
    Server_id: "500801000000004",
    EvnDirection_Num: "1058657",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "12:30",
    Lpu_Nick: 'ГБУЗ МО "Орехово-Зуевская областная больница"',
    Lpu_id: "500801000000004",
    RiskType_id: null,
    Person_Fin: "Якоева ЕВ",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ИОНОВА НАТАЛИЯ ВЛАДИМИРОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) диагноза ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239037797",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "07.09.2023 14:30",
    deadDiff: "19",
    DirType_Code: "13",
    EvnQueue_id: "500801238572229",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "3",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "345912332661",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "2",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
    EvnDirection_id: "500801239268778",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238984656",
    EvnDirection_rid: "500801238980951",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5577",
    Person_id: "8053339",
    PersonEvn_id: "66239661",
    Server_id: "0",
    EvnDirection_Num: "852196",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:25",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "СТОЛБУН РАИСА МАКСИМОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:25",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239268777",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "2",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "J18.9. Пневмония неуточненная",
    EvnDirection_id: "500801239514547",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801226200483",
    EvnDirection_rid: "500801226200480",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239561549",
    ConsultingForm_Name: "Онлайн-чат",
    Diag_id: "5775",
    Person_id: "1107009",
    PersonEvn_id: "500801041258811",
    Server_id: "13101161",
    EvnDirection_Num: "398049",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "15:06",
    Lpu_Nick: 'ГБУЗ Московской области "ЦГКБ г.Реутов"',
    Lpu_id: "13101161",
    RiskType_id: null,
    Person_Fin: "НАЙДЕНОВА АВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "ПЕСТРИКОВА ВИКТОРИЯ ВИКТОРОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239561549",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 15:06",
    deadDiff: "22",
    DirType_Code: "13",
    EvnQueue_id: "500801239514546",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "1",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "420906582583",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "3",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "K92.2. Желудочно-кишечное кровотечение неуточненное",
    EvnDirection_id: "500801239446538",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801230698709",
    EvnDirection_rid: "500801230675454",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239517998",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "6334",
    Person_id: "6881704",
    PersonEvn_id: "59205294",
    Server_id: "0",
    EvnDirection_Num: "762989",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "14:04",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ЕЛАНСКОВА ОЛЬГА СЕРГЕЕВНА",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239517998",
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 16:04",
    deadDiff: "45",
    DirType_Code: "13",
    EvnQueue_id: "500801239446537",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "A46. Рожа",
    EvnDirection_id: "500801239125035",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238161658",
    EvnDirection_rid: "500801238150221",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239347657",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "11508",
    Person_id: "1693744",
    PersonEvn_id: "500801032594575",
    Server_id: "13100943",
    EvnDirection_Num: "534512",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "09:23",
    Lpu_Nick: "МЫТИЩИНСКАЯ ГОРОДСКАЯ КЛИНИЧЕСКАЯ БОЛЬНИЦА",
    Lpu_id: "13100932",
    RiskType_id: null,
    Person_Fin: "БАЗУНОВА ВА",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ОРЛОВА ТАТЬЯНА ВИКТОРОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) диагноза ",
    LpuSectionProfile_Name: "ревматологии",
    UslugaTelemedResultType_Name: "Дообследование с повторной консультацией",
    ConsultationForm_Code: "1",
    ConsultationForm_Name: "Плановая",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239347657",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "22.09.2023 09:23",
    deadDiff: "328",
    DirType_Code: "13",
    EvnQueue_id: "500801239125034",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Дообследование с повторной консультацией",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "3",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "433700669024",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I80.0. Флебит и тромбофлебит поверхностных сосудов нижних конечностей",
    EvnDirection_id: "500801239399551",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801235688423",
    EvnDirection_rid: "500801235688407",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5661",
    Person_id: "500801003357917",
    PersonEvn_id: "500801042827632",
    Server_id: "13101156",
    EvnDirection_Num: "762910",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:15",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
    Person_FIO: "ГУЛЯЕВ ЕВГЕНИЙ АЛЕКСАНДРОВИЧ",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "хирургии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 15:15",
    deadDiff: "44",
    DirType_Code: "13",
    EvnQueue_id: "500801239399550",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
    EvnDirection_id: "500801239294275",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238870954",
    EvnDirection_rid: "500801238853064",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5577",
    Person_id: "7984720",
    PersonEvn_id: "500801043399859",
    Server_id: "13101027",
    EvnDirection_Num: "852316",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:45",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "РУМЯНЦЕВ НИКОЛАЙ ВЛАДИМИРОВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:45",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239294274",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "2",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801239308404",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238844611",
    EvnDirection_rid: "500801238828667",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239373563",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "4599782",
    PersonEvn_id: "500801043395824",
    Server_id: "13101027",
    EvnDirection_Num: "852371",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:57",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "КАТКОВА АНТОНИНА ПЕТРОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239373563",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:57",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239308402",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801239309763",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238844611",
    EvnDirection_rid: "500801238828667",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "4599782",
    PersonEvn_id: "500801043395824",
    Server_id: "13101027",
    EvnDirection_Num: "852377",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:58",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "КАТКОВА АНТОНИНА ПЕТРОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:58",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239309762",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "2",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "K92.2. Желудочно-кишечное кровотечение неуточненное",
    EvnDirection_id: "500801239448352",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801230698709",
    EvnDirection_rid: "500801230675454",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "6334",
    Person_id: "6881704",
    PersonEvn_id: "59205294",
    Server_id: "0",
    EvnDirection_Num: "762999",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "14:06",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
    Person_FIO: "ЕЛАНСКОВА ОЛЬГА СЕРГЕЕВНА",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "нефрологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 16:06",
    deadDiff: "45",
    DirType_Code: "13",
    EvnQueue_id: "500801239448351",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801239404151",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801239182906",
    EvnDirection_rid: "500801239117991",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "5006076",
    PersonEvn_id: "500801043444886",
    Server_id: "13101027",
    EvnDirection_Num: "852831",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:19",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "БОГУНОВА НАДЕЖДА ИВАНОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: "2023-09-08 13:19:48",
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 13:19",
    deadDiff: "20",
    DirType_Code: "13",
    EvnQueue_id: "500801239404150",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: "Отказ пациента (его законного представителя)",
    evndirection_result: "Отказ пациента",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Canceled",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "5",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I80.0. Флебит и тромбофлебит поверхностных сосудов нижних конечностей",
    EvnDirection_id: "500801239400617",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801235688423",
    EvnDirection_rid: "500801235688407",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5661",
    Person_id: "500801003357917",
    PersonEvn_id: "500801042827632",
    Server_id: "13101156",
    EvnDirection_Num: "762914",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:16",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
    Person_FIO: "ГУЛЯЕВ ЕВГЕНИЙ АЛЕКСАНДРОВИЧ",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "терапии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 15:16",
    deadDiff: "44",
    DirType_Code: "13",
    EvnQueue_id: "500801239400616",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
    EvnDirection_id: "500801239293609",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238870954",
    EvnDirection_rid: "500801238853064",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239369877",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5577",
    Person_id: "7984720",
    PersonEvn_id: "500801043399859",
    Server_id: "13101027",
    EvnDirection_Num: "852311",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:45",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "РУМЯНЦЕВ НИКОЛАЙ ВЛАДИМИРОВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239369877",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:45",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239293608",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "T07. Множественные травмы неуточненные",
    EvnDirection_id: "500801239434245",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238930404",
    EvnDirection_rid: "500801238930388",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239504243",
    ConsultingForm_Name: "Онлайн",
    Diag_id: "11702",
    Person_id: "500801003356077",
    PersonEvn_id: "500801042789862",
    Server_id: "13101072",
    EvnDirection_Num: "952412",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:51",
    Lpu_Nick: 'ГБУЗ МО "ВРКБ"',
    Lpu_id: "13100903",
    RiskType_id: null,
    Person_Fin: "МОНГУШ АА",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "СЕЛЬМАНОВИЧ АЛЕКСАНДР ЛЕОНИДОВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239504243",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 15:51",
    deadDiff: "44",
    DirType_Code: "13",
    EvnQueue_id: "500801239434244",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "363459999167",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "2",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I25.2. Перенесенный в прошлом инфаркт миокарда",
    EvnDirection_id: "500801239307323",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801236737140",
    EvnDirection_rid: "500801236732167",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5419",
    Person_id: "2715869",
    PersonEvn_id: "500801043006306",
    Server_id: "13101283",
    EvnDirection_Num: "2014146",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:56",
    Lpu_Nick: 'ГБУЗ МО "ЛЮБЕРЕЦКАЯ ОБ"',
    Lpu_id: "13101283",
    RiskType_id: null,
    Person_Fin: "ПАРШИКОВА ЕН",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ОБУХОВ АЛЕКСАНДР ЮРЬЕВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "сердечно-сосудистой хирургии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:56",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239307322",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "347280479071",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I80.0. Флебит и тромбофлебит поверхностных сосудов нижних конечностей",
    EvnDirection_id: "500801239397791",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801235688423",
    EvnDirection_rid: "500801235688407",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5661",
    Person_id: "500801003357917",
    PersonEvn_id: "500801042827632",
    Server_id: "13101156",
    EvnDirection_Num: "762907",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:14",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
    Person_FIO: "ГУЛЯЕВ ЕВГЕНИЙ АЛЕКСАНДРОВИЧ",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "нефрологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 15:14",
    deadDiff: "44",
    DirType_Code: "13",
    EvnQueue_id: "500801239397790",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "J12.8. Другая вирусная пневмония",
    EvnDirection_id: "500801239449158",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801230698709",
    EvnDirection_rid: "500801230675454",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5752",
    Person_id: "6881704",
    PersonEvn_id: "59205294",
    Server_id: "0",
    EvnDirection_Num: "763001",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "14:07",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
    Person_FIO: "ЕЛАНСКОВА ОЛЬГА СЕРГЕЕВНА",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "пульмонологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 16:07",
    deadDiff: "45",
    DirType_Code: "13",
    EvnQueue_id: "500801239449155",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "S21.1. Открытая рана передней стенки грудной клетки",
    EvnDirection_id: "500801239031680",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801239012397",
    EvnDirection_rid: "500801239004021",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239081019",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "9413",
    Person_id: "500801003384482",
    PersonEvn_id: "500801043423650",
    Server_id: "13101072",
    EvnDirection_Num: "1121082",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "07:53",
    Lpu_Nick: 'ГБУЗ Московской области "Домодедовская больница"',
    Lpu_id: "13101072",
    RiskType_id: null,
    Person_Fin: "ЯЦКОВА НГ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "АВСАЛИМОВ ИГОРЬ МИХАЙЛОВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Другое",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239081019",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 07:53",
    deadDiff: "14",
    DirType_Code: "13",
    EvnQueue_id: "500801239031679",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "4",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "355243092210",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "K85.9. Острый панкреатит неуточненный",
    EvnDirection_id: "500801239450303",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238971198",
    EvnDirection_rid: "500801238496658",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239515319",
    ConsultingForm_Name: "Онлайн",
    Diag_id: "15264",
    Person_id: "500801003380131",
    PersonEvn_id: "500801043390325",
    Server_id: "13100903",
    EvnDirection_Num: "952465",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "14:08",
    Lpu_Nick: 'ГБУЗ МО "ВРКБ"',
    Lpu_id: "13100903",
    RiskType_id: null,
    Person_Fin: "МОНГУШ АА",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "ШАШ РУСЛАН ВИТАЛЬЕВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239515319",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 16:08",
    deadDiff: "45",
    DirType_Code: "13",
    EvnQueue_id: "500801239450302",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "363459999167",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "2",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I42.0. Дилатационная кардиомиопатия",
    EvnDirection_id: "500801239447574",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801230698709",
    EvnDirection_rid: "500801230675454",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5485",
    Person_id: "6881704",
    PersonEvn_id: "59205294",
    Server_id: "0",
    EvnDirection_Num: "762995",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "14:05",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
    Person_FIO: "ЕЛАНСКОВА ОЛЬГА СЕРГЕЕВНА",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "кардиологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 16:05",
    deadDiff: "45",
    DirType_Code: "13",
    EvnQueue_id: "500801239447573",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801239405008",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801239182906",
    EvnDirection_rid: "500801239117991",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "5006076",
    PersonEvn_id: "500801043444886",
    Server_id: "13101027",
    EvnDirection_Num: "852838",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:20",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "БОГУНОВА НАДЕЖДА ИВАНОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 13:20",
    deadDiff: "20",
    DirType_Code: "13",
    EvnQueue_id: "500801239405007",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "2",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
    EvnDirection_id: "500801239268374",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238984656",
    EvnDirection_rid: "500801238980951",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239371747",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5577",
    Person_id: "8053339",
    PersonEvn_id: "66239661",
    Server_id: "0",
    EvnDirection_Num: "852192",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:24",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "СТОЛБУН РАИСА МАКСИМОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239371747",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:24",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239268373",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I80.0. Флебит и тромбофлебит поверхностных сосудов нижних конечностей",
    EvnDirection_id: "500801239396771",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801235688423",
    EvnDirection_rid: "500801235688407",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239456996",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5661",
    Person_id: "500801003357917",
    PersonEvn_id: "500801042827632",
    Server_id: "13101156",
    EvnDirection_Num: "762905",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:13",
    Lpu_Nick: "ГБУЗ МО «СОКБ»",
    Lpu_id: "13101156",
    RiskType_id: null,
    Person_Fin: "ГОЛОВИН ВВ",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ГУЛЯЕВ ЕВГЕНИЙ АЛЕКСАНДРОВИЧ",
    EvnDirection_IsCito: "true",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239456996",
    evndirection_iscito_fororder: "2",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 15:13",
    deadDiff: "44",
    DirType_Code: "13",
    EvnQueue_id: "500801239396770",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "419862796350",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
    EvnDirection_id: "500801239403663",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801239182906",
    EvnDirection_rid: "500801239117991",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239501909",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5574",
    Person_id: "5006076",
    PersonEvn_id: "500801043444886",
    Server_id: "13101027",
    EvnDirection_Num: "852830",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:19",
    Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
    Lpu_id: "13101027",
    RiskType_id: null,
    Person_Fin: "ЩЕРБЕНЕВ ЕВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "БОГУНОВА НАДЕЖДА ИВАНОВНА",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239501909",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 13:19",
    deadDiff: "20",
    DirType_Code: "13",
    EvnQueue_id: "500801239403662",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "440255061849",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I25.2. Перенесенный в прошлом инфаркт миокарда",
    EvnDirection_id: "500801239309910",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801236737140",
    EvnDirection_rid: "500801236732167",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "5419",
    Person_id: "2715869",
    PersonEvn_id: "500801043006306",
    Server_id: "13101283",
    EvnDirection_Num: "2014174",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "11:58",
    Lpu_Nick: 'ГБУЗ МО "ЛЮБЕРЕЦКАЯ ОБ"',
    Lpu_id: "13101283",
    RiskType_id: null,
    Person_Fin: "ПАРШИКОВА ЕН",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ОБУХОВ АЛЕКСАНДР ЮРЬЕВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "кардиологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 11:58",
    deadDiff: "18",
    DirType_Code: "13",
    EvnQueue_id: "500801239309909",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "347280479071",
    UslugaComplex_did: null,
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "J94.8. Другие уточненные плевральные состояния",
    EvnDirection_id: "500801239396932",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801237685737",
    EvnDirection_rid: "500801237685699",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239453981",
    ConsultingForm_Name: "Онлайн-чат",
    Diag_id: "5910",
    Person_id: "500801003373489",
    PersonEvn_id: "500801043185793",
    Server_id: "13101161",
    EvnDirection_Num: "397850",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:13",
    Lpu_Nick: 'ГБУЗ Московской области "ЦГКБ г.Реутов"',
    Lpu_id: "13101161",
    RiskType_id: null,
    Person_Fin: "НАЙДЕНОВА АВ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "ЮРИН АНДРЕЙ ВЛАДИМРОВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239453981",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 13:13",
    deadDiff: "20",
    DirType_Code: "13",
    EvnQueue_id: "500801239396931",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "1",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "11380",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "420906582583",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "3",
  },
  {
    EvnClass_id: "27",
    Diag_FullName:
      "N12. Тубулоинтерстициальный нефрит, не уточненный как острый или хронический",
    EvnDirection_id: "500801238502835",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801230724680",
    EvnDirection_rid: "500801230724674",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239027020",
    ConsultingForm_Name: "Онлайн-чат",
    Diag_id: "11639",
    Person_id: "500801001006508",
    PersonEvn_id: "500801009542048",
    Server_id: "13101214",
    EvnDirection_Num: "209106",
    PayType_id: "201",
    EvnDirection_setDT: "07.09.2023",
    EvnDirection_insDate: "07.09.2023",
    EvnDirection_insTime: "11:37",
    Lpu_Nick: 'ГБУЗ МО "ЛЦГБ"',
    Lpu_id: "13100880",
    RiskType_id: null,
    Person_Fin: "ТОКАРЕВА ТА",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "КРЮКОВ ДЕНИС МИХАЙЛОВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "нефрологии",
    UslugaTelemedResultType_Name: "Дообследование с повторной консультацией",
    ConsultationForm_Code: "1",
    ConsultationForm_Name: "Плановая",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239027020",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-07 00:00:00",
    deadLine: "21.09.2023 11:37",
    deadDiff: "306",
    DirType_Code: "13",
    EvnQueue_id: "500801238502834",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Дообследование с повторной консультацией",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "1",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "500801000003930",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "414202223785",
    UslugaComplex_did: "4743922",
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "3",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "I48.1. Постоянная форма фибрилляции предсердий",
    EvnDirection_id: "500801239329310",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801236823092",
    EvnDirection_rid: "500801236763729",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "15322",
    Person_id: "4792777",
    PersonEvn_id: "60561744",
    Server_id: "0",
    EvnDirection_Num: "536047",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "12:15",
    Lpu_Nick: 'ГБУЗ МО "МОБ ИМ. ПРОФ. РОЗАНОВА В.Н.',
    Lpu_id: "500801000000012",
    RiskType_id: null,
    Person_Fin: "ГЛУШКОВА ВД",
    MedPersonalFIO_whom_sent: "АЛЛАХВЕРДЯН НН",
    Person_FIO: "ДЕНИСОВ ЮРИЙ ГЕОРГИЕВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name:
      "Необходимость выполнение нового и/или редкого вида оперативного вмешательства, процедуры и т.д. ",
    LpuSectionProfile_Name: "сердечно-сосудистой хирургии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "1",
    ConsultationForm_Name: "Плановая",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "22.09.2023 12:15",
    deadDiff: "331",
    DirType_Code: "13",
    EvnQueue_id: "500801239329308",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "500801000003930",
    Org_tid: "13101155",
    RemoteConsultCause_id: "5",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "348072343710",
    UslugaComplex_did: "4743923",
    evndirection_group: "3",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "G61.9. Воспалительная полиневропатия неуточненная",
    EvnDirection_id: "500801239418712",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238940867",
    EvnDirection_rid: "500801232558435",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Офлайн",
    Diag_id: "4867",
    Person_id: "500801003328102",
    PersonEvn_id: "500801042240357",
    Server_id: "13101068",
    EvnDirection_Num: "1316422",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "13:36",
    Lpu_Nick: 'ГБУЗ МО "Солнечногорская областная больница"',
    Lpu_id: "13101068",
    RiskType_id: null,
    Person_Fin: "АЛИЕВА ГИ",
    MedPersonalFIO_whom_sent: "ГЕВОРКЯН АА",
    Person_FIO: "Гаврилов Сергей Викторович",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) диагноза ",
    LpuSectionProfile_Name: "неврологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: "2023-09-08 14:08:34",
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 15:36",
    deadDiff: "44",
    DirType_Code: "13",
    EvnQueue_id: "500801239418711",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: "Непредоставление необходимого пакета документов",
    evndirection_result: "Нет показаний для госпитализации",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "500801000003930",
    Org_tid: "13101155",
    RemoteConsultCause_id: "3",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Canceled",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "381240562349",
    UslugaComplex_did: null,
    evndirection_group: "5",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "C92.0. Острый миелобластный лейкоз [ОМЛ]",
    EvnDirection_id: "500801239365769",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801234230131",
    EvnDirection_rid: "500801234229604",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: null,
    ConsultingForm_Name: "Онлайн-чат",
    Diag_id: "3458",
    Person_id: "5000188",
    PersonEvn_id: "500801041520738",
    Server_id: "1",
    EvnDirection_Num: "796573",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "12:45",
    Lpu_Nick: 'ГБУЗ МОСКОВСКОЙ ОБЛАСТИ "КЛИНСКАЯ ОБЛАСТНАЯ БОЛЬНИЦА"',
    Lpu_id: "13101138",
    RiskType_id: null,
    Person_Fin: "ХОМЕНКО ЕА",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "Ванин Виктор Егорович",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "гематологии",
    UslugaTelemedResultType_Name: null,
    ConsultationForm_Code: "3",
    ConsultationForm_Name: "Экстренная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: null,
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "08.09.2023 14:45",
    deadDiff: "43",
    DirType_Code: "13",
    EvnQueue_id: "500801239365768",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: null,
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "1",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "500801000003930",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Queued",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "344601748297",
    UslugaComplex_did: null,
    evndirection_group: "2",
    TimeTable_begTime: null,
    ConsultingForm_id: "3",
  },
  {
    EvnClass_id: "27",
    Diag_FullName: "K70.2. Алкогольный фиброз и склероз печени",
    EvnDirection_id: "500801239000726",
    EvnDirection_IsConcilium: "1",
    EvnDirection_pid: "500801238438678",
    EvnDirection_rid: "500801235094763",
    RootEvnClass_SysNick: "EvnPS",
    EvnUslugaTelemed_id: "500801239070566",
    ConsultingForm_Name: "Офлайн",
    Diag_id: "6236",
    Person_id: "4155075",
    PersonEvn_id: "40796759",
    Server_id: "0",
    EvnDirection_Num: "533932",
    PayType_id: "201",
    EvnDirection_setDT: "08.09.2023",
    EvnDirection_insDate: "08.09.2023",
    EvnDirection_insTime: "01:24",
    Lpu_Nick: "МЫТИЩИНСКАЯ ГОРОДСКАЯ КЛИНИЧЕСКАЯ БОЛЬНИЦА",
    Lpu_id: "13100932",
    RiskType_id: null,
    Person_Fin: "КИПКЕЕВА ФХ",
    MedPersonalFIO_whom_sent: null,
    Person_FIO: "ПРУДОВ ВИКТОР СЕРГЕЕВИЧ",
    EvnDirection_IsCito: "false",
    RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
    LpuSectionProfile_Name: "анестезиологии и реаниматологии",
    UslugaTelemedResultType_Name:
      "Подтверждение диагноза без коррекции лечения",
    ConsultationForm_Code: "2",
    ConsultationForm_Name: "Неотложная",
    isDel: "1",
    evndirection_faildt_fororder: null,
    evnuslugatelemed_id_fororder: "500801239070566",
    evndirection_iscito_fororder: "1",
    evndirection_setdt_fororder: "2023-09-08 00:00:00",
    deadLine: "09.09.2023 01:24",
    deadDiff: "8",
    DirType_Code: "13",
    EvnQueue_id: "500801239000725",
    TimeTableStac_id: null,
    TimeTableGraf_id: null,
    TimeTableMedService_id: null,
    EvnStatusCause_Name: null,
    evndirection_result: "Подтверждение диагноза без коррекции лечения",
    EvnXml_id: null,
    EvnXml_IsSigned: null,
    EvnXml_signDT: null,
    pmUser_signName: null,
    RequestConsult_id: "2",
    EvnConcilium_id: null,
    ConciliumType_id: null,
    MedService_id: "500801000003930",
    Org_tid: "13101155",
    RemoteConsultCause_id: "2",
    RecMethodType_id: "10",
    EvnDirection_isAuto: "1",
    Evn_IsSigned: null,
    Evn_signDT: null,
    EvnConciliumStatus_SysNick: null,
    EvnDirectionStatus_SysNick: "Serviced",
    isConciliumMember: "1",
    ConciliumResults_id: null,
    pmUser_insID: "435321307951",
    UslugaComplex_did: null,
    evndirection_group: "4",
    TimeTable_begTime: null,
    ConsultingForm_id: "1",
  },
];

const RequestStateContainer = observer(() => {
  const { request } = useContext(Context);
  const sortedRequests = sortRequests(requests, request.selectedState);
  const specialties = combineOnlySpecialties(sortedRequests);
  return (
    <Card>
      <Card.Header className="d-flex justify-content-between">
        <Nav variant="tabs" defaultActiveKey={`#${request.states[0].link}`}>
          {request.states.map((state) => (
            <Nav.Item key={state.id}>
              <Nav.Link
                href={`#${state.link}`}
                onClick={() => request.setSelectedState(state.state)}
              >
                {state.name}
              </Nav.Link>
            </Nav.Item>
          ))}
        </Nav>
      </Card.Header>
      <Card.Body>
        <Row xxl={2} xl={2} lg={2} sm={1} xs={1} className="g-3">
          {sortedRequests.map((request) => {
            let specs;
            for (let spec of Object.keys(specialties)) {
              if (request["Person_id"] === spec) {
                specs = specialties[spec];
              }
            }
            return (
              <PatientCard
                key={`${request["EvnDirection_id"]}`}
                request={request}
                specialties={specs}
              />
            );
          })}
        </Row>
      </Card.Body>
    </Card>
  );
});

export default RequestStateContainer;
