import { makeAutoObservable } from "mobx";
// const emias = require("../../../server/emias");

export default class RequestStore {
  constructor(props) {
    this._states = [
      { id: 1, name: "В работе", status: "Queued", link: "queued" },
      { id: 2, name: "Выполнено", status: "Serviced", link: "serviced" },
      { id: 3, name: "Отменено", status: "Canceled", link: "canceled" },
    ];
    // this._requests = emias.loadWork();
    this._requests = [
      {
        EvnClass_id: "27",
        Diag_FullName:
          "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
        EvnDirection_id: "500801238498941",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801237995372",
        EvnDirection_rid: "500801237955015",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: "500801238997071",
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5574",
        Person_id: "3983387",
        PersonEvn_id: "500801043233861",
        Server_id: "13101027",
        EvnDirection_Num: "847818",
        PayType_id: "201",
        EvnDirection_setDT: "07.09.2023",
        EvnDirection_insDate: "07.09.2023",
        EvnDirection_insTime: "11:34",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "СОЛЕНОВА ВЕРА МИХАЙЛОВНА",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "неврологии",
        UslugaTelemedResultType_Name:
          "Подтверждение диагноза без коррекции лечения",
        ConsultationForm_Code: "2",
        ConsultationForm_Name: "Неотложная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: "500801238997071",
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-07 00:00:00",
        deadLine: "08.09.2023 11:34",
        deadDiff: "5",
        DirType_Code: "13",
        EvnQueue_id: "500801238498940",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: "Подтверждение диагноза без коррекции лечения",
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Serviced",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "4",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName:
          "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
        EvnDirection_id: "500801238483602",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801238133682",
        EvnDirection_rid: "500801238126295",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: "500801238996553",
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5574",
        Person_id: "500801002104543",
        PersonEvn_id: "500801043263205",
        Server_id: "13101027",
        EvnDirection_Num: "847748",
        PayType_id: "201",
        EvnDirection_setDT: "07.09.2023",
        EvnDirection_insDate: "07.09.2023",
        EvnDirection_insTime: "11:23",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "Еремин Василий Степанович",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "неврологии",
        UslugaTelemedResultType_Name:
          "Подтверждение диагноза без коррекции лечения",
        ConsultationForm_Code: "2",
        ConsultationForm_Name: "Неотложная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: "500801238996553",
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-07 00:00:00",
        deadLine: "08.09.2023 11:23",
        deadDiff: "5",
        DirType_Code: "13",
        EvnQueue_id: "500801238483601",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: "Подтверждение диагноза без коррекции лечения",
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Serviced",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "4",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
        EvnDirection_id: "500801238704781",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801238634033",
        EvnDirection_rid: "500801238580826",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: "500801238998112",
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5577",
        Person_id: "500801003380785",
        PersonEvn_id: "500801043349985",
        Server_id: "13101027",
        EvnDirection_Num: "849009",
        PayType_id: "201",
        EvnDirection_setDT: "07.09.2023",
        EvnDirection_insDate: "07.09.2023",
        EvnDirection_insTime: "14:15",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "КРАУСОВА АЛЕКСАНДРА АЛЕКСЕЕВНА",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "неврологии",
        UslugaTelemedResultType_Name:
          "Подтверждение диагноза без коррекции лечения",
        ConsultationForm_Code: "2",
        ConsultationForm_Name: "Неотложная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: "500801238998112",
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-07 00:00:00",
        deadLine: "08.09.2023 14:15",
        deadDiff: "2",
        DirType_Code: "13",
        EvnQueue_id: "500801238704779",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: "Подтверждение диагноза без коррекции лечения",
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Serviced",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "4",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName:
          "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
        EvnDirection_id: "500801238742006",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801238667698",
        EvnDirection_rid: "500801238605995",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: "500801238999079",
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5574",
        Person_id: "5463106",
        PersonEvn_id: "500801043354958",
        Server_id: "13101027",
        EvnDirection_Num: "849222",
        PayType_id: "201",
        EvnDirection_setDT: "07.09.2023",
        EvnDirection_insDate: "07.09.2023",
        EvnDirection_insTime: "14:46",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "ВЕКШИНА НАДЕЖДА ВАСИЛЬЕВНА",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "неврологии",
        UslugaTelemedResultType_Name:
          "Подтверждение диагноза без коррекции лечения",
        ConsultationForm_Code: "1",
        ConsultationForm_Name: "Плановая",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: "500801238999079",
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-07 00:00:00",
        deadLine: "21.09.2023 14:46",
        deadDiff: "309",
        DirType_Code: "13",
        EvnQueue_id: "500801238742005",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: "Подтверждение диагноза без коррекции лечения",
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Serviced",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "4",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName:
          "E10.7. Инсулинзависимый сахарный диабет с множественными осложнениями",
        EvnDirection_id: "500801238989132",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801232666344",
        EvnDirection_rid: "500801232666333",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: null,
        ConsultingForm_Name: "Офлайн",
        Diag_id: "3978",
        Person_id: "3048049",
        PersonEvn_id: "44100598",
        Server_id: "0",
        EvnDirection_Num: "523252",
        PayType_id: "201",
        EvnDirection_setDT: "07.09.2023",
        EvnDirection_insDate: "07.09.2023",
        EvnDirection_insTime: "23:38",
        Lpu_Nick: 'ГБУЗ МО "КОЛОМЕНСКАЯ ОБЛАСТНАЯ БОЛЬНИЦА"',
        Lpu_id: "500801000000014",
        RiskType_id: null,
        Person_Fin: "ЕРМИЛОВ ВЮ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "КРЮЧКОВА МАРИЯ СЕРГЕЕВНА",
        EvnDirection_IsCito: "true",
        RemoteConsultCause_Name: "Другое",
        LpuSectionProfile_Name: "пульмонологии",
        UslugaTelemedResultType_Name: null,
        ConsultationForm_Code: "3",
        ConsultationForm_Name: "Экстренная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: null,
        evndirection_iscito_fororder: "2",
        evndirection_setdt_fororder: "2023-09-07 00:00:00",
        deadLine: "08.09.2023 01:38",
        deadDiff: "30",
        DirType_Code: "13",
        EvnQueue_id: "500801238989131",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: null,
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "4",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Queued",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "348425304652",
        UslugaComplex_did: null,
        evndirection_group: "2",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
        EvnDirection_id: "500801239268778",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801238984656",
        EvnDirection_rid: "500801238980951",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: null,
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5577",
        Person_id: "8053339",
        PersonEvn_id: "66239661",
        Server_id: "0",
        EvnDirection_Num: "852196",
        PayType_id: "201",
        EvnDirection_setDT: "08.09.2023",
        EvnDirection_insDate: "08.09.2023",
        EvnDirection_insTime: "11:25",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "СТОЛБУН РАИСА МАКСИМОВНА",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "неврологии",
        UslugaTelemedResultType_Name: null,
        ConsultationForm_Code: "2",
        ConsultationForm_Name: "Неотложная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: null,
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-08 00:00:00",
        deadLine: "09.09.2023 11:25",
        deadDiff: "18",
        DirType_Code: "13",
        EvnQueue_id: "500801239268777",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: null,
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Queued",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "2",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName:
          "I80.0. Флебит и тромбофлебит поверхностных сосудов нижних конечностей",
        EvnDirection_id: "500801239399551",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801235688423",
        EvnDirection_rid: "500801235688407",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: null,
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5661",
        Person_id: "500801003357917",
        PersonEvn_id: "500801042827632",
        Server_id: "13101156",
        EvnDirection_Num: "762910",
        PayType_id: "201",
        EvnDirection_setDT: "08.09.2023",
        EvnDirection_insDate: "08.09.2023",
        EvnDirection_insTime: "13:15",
        Lpu_Nick: "ГБУЗ МО «СОКБ»",
        Lpu_id: "13101156",
        RiskType_id: null,
        Person_Fin: "ГОЛОВИН ВВ",
        MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
        Person_FIO: "ГУЛЯЕВ ЕВГЕНИЙ АЛЕКСАНДРОВИЧ",
        EvnDirection_IsCito: "true",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "хирургии",
        UslugaTelemedResultType_Name: null,
        ConsultationForm_Code: "3",
        ConsultationForm_Name: "Экстренная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: null,
        evndirection_iscito_fororder: "2",
        evndirection_setdt_fororder: "2023-09-08 00:00:00",
        deadLine: "08.09.2023 15:15",
        deadDiff: "44",
        DirType_Code: "13",
        EvnQueue_id: "500801239399550",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: null,
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Queued",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "419862796350",
        UslugaComplex_did: null,
        evndirection_group: "3",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName: "I63.9. Инфаркт мозга неуточненный",
        EvnDirection_id: "500801239294275",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801238870954",
        EvnDirection_rid: "500801238853064",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: null,
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5577",
        Person_id: "7984720",
        PersonEvn_id: "500801043399859",
        Server_id: "13101027",
        EvnDirection_Num: "852316",
        PayType_id: "201",
        EvnDirection_setDT: "08.09.2023",
        EvnDirection_insDate: "08.09.2023",
        EvnDirection_insTime: "11:45",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "РУМЯНЦЕВ НИКОЛАЙ ВЛАДИМИРОВИЧ",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "неврологии",
        UslugaTelemedResultType_Name: null,
        ConsultationForm_Code: "2",
        ConsultationForm_Name: "Неотложная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: null,
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-08 00:00:00",
        deadLine: "09.09.2023 11:45",
        deadDiff: "18",
        DirType_Code: "13",
        EvnQueue_id: "500801239294274",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: null,
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Queued",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "2",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName:
          "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
        EvnDirection_id: "500801239309763",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801238844611",
        EvnDirection_rid: "500801238828667",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: null,
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5574",
        Person_id: "4599782",
        PersonEvn_id: "500801043395824",
        Server_id: "13101027",
        EvnDirection_Num: "852377",
        PayType_id: "201",
        EvnDirection_setDT: "08.09.2023",
        EvnDirection_insDate: "08.09.2023",
        EvnDirection_insTime: "11:58",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "КАТКОВА АНТОНИНА ПЕТРОВНА",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "неврологии",
        UslugaTelemedResultType_Name: null,
        ConsultationForm_Code: "2",
        ConsultationForm_Name: "Неотложная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: null,
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-08 00:00:00",
        deadLine: "09.09.2023 11:58",
        deadDiff: "18",
        DirType_Code: "13",
        EvnQueue_id: "500801239309762",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: null,
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Queued",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "2",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName: "K92.2. Желудочно-кишечное кровотечение неуточненное",
        EvnDirection_id: "500801239448352",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801230698709",
        EvnDirection_rid: "500801230675454",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: null,
        ConsultingForm_Name: "Офлайн",
        Diag_id: "6334",
        Person_id: "6881704",
        PersonEvn_id: "59205294",
        Server_id: "0",
        EvnDirection_Num: "762999",
        PayType_id: "201",
        EvnDirection_setDT: "08.09.2023",
        EvnDirection_insDate: "08.09.2023",
        EvnDirection_insTime: "14:06",
        Lpu_Nick: "ГБУЗ МО «СОКБ»",
        Lpu_id: "13101156",
        RiskType_id: null,
        Person_Fin: "ГОЛОВИН ВВ",
        MedPersonalFIO_whom_sent: "БАЛКАНОВ АС",
        Person_FIO: "ЕЛАНСКОВА ОЛЬГА СЕРГЕЕВНА",
        EvnDirection_IsCito: "true",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "нефрологии",
        UslugaTelemedResultType_Name: null,
        ConsultationForm_Code: "3",
        ConsultationForm_Name: "Экстренная",
        isDel: "1",
        evndirection_faildt_fororder: null,
        evnuslugatelemed_id_fororder: null,
        evndirection_iscito_fororder: "2",
        evndirection_setdt_fororder: "2023-09-08 00:00:00",
        deadLine: "08.09.2023 16:06",
        deadDiff: "45",
        DirType_Code: "13",
        EvnQueue_id: "500801239448351",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: null,
        evndirection_result: null,
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Queued",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "419862796350",
        UslugaComplex_did: null,
        evndirection_group: "3",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
      {
        EvnClass_id: "27",
        Diag_FullName:
          "I63.5. Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий",
        EvnDirection_id: "500801239404151",
        EvnDirection_IsConcilium: "1",
        EvnDirection_pid: "500801239182906",
        EvnDirection_rid: "500801239117991",
        RootEvnClass_SysNick: "EvnPS",
        EvnUslugaTelemed_id: null,
        ConsultingForm_Name: "Офлайн",
        Diag_id: "5574",
        Person_id: "5006076",
        PersonEvn_id: "500801043444886",
        Server_id: "13101027",
        EvnDirection_Num: "852831",
        PayType_id: "201",
        EvnDirection_setDT: "08.09.2023",
        EvnDirection_insDate: "08.09.2023",
        EvnDirection_insTime: "13:19",
        Lpu_Nick: 'ГБУЗ МО "СЕРГИЕВО-ПОСАДСКАЯ РБ"',
        Lpu_id: "13101027",
        RiskType_id: null,
        Person_Fin: "ЩЕРБЕНЕВ ЕВ",
        MedPersonalFIO_whom_sent: null,
        Person_FIO: "БОГУНОВА НАДЕЖДА ИВАНОВНА",
        EvnDirection_IsCito: "false",
        RemoteConsultCause_Name: "Определение (подтверждение) тактики лечения ",
        LpuSectionProfile_Name: "анестезиологии и реаниматологии",
        UslugaTelemedResultType_Name: null,
        ConsultationForm_Code: "2",
        ConsultationForm_Name: "Неотложная",
        isDel: "1",
        evndirection_faildt_fororder: "2023-09-08 13:19:48",
        evnuslugatelemed_id_fororder: null,
        evndirection_iscito_fororder: "1",
        evndirection_setdt_fororder: "2023-09-08 00:00:00",
        deadLine: "09.09.2023 13:19",
        deadDiff: "20",
        DirType_Code: "13",
        EvnQueue_id: "500801239404150",
        TimeTableStac_id: null,
        TimeTableGraf_id: null,
        TimeTableMedService_id: null,
        EvnStatusCause_Name: "Отказ пациента (его законного представителя)",
        evndirection_result: "Отказ пациента",
        EvnXml_id: null,
        EvnXml_IsSigned: null,
        EvnXml_signDT: null,
        pmUser_signName: null,
        RequestConsult_id: "2",
        EvnConcilium_id: null,
        ConciliumType_id: null,
        MedService_id: "11380",
        Org_tid: "13101155",
        RemoteConsultCause_id: "2",
        RecMethodType_id: "10",
        EvnDirection_isAuto: "1",
        Evn_IsSigned: null,
        Evn_signDT: null,
        EvnConciliumStatus_SysNick: null,
        EvnDirectionStatus_SysNick: "Canceled",
        isConciliumMember: "1",
        ConciliumResults_id: null,
        pmUser_insID: "440255061849",
        UslugaComplex_did: null,
        evndirection_group: "5",
        TimeTable_begTime: null,
        ConsultingForm_id: "1",
      },
    ];
    this._selectedState = "Queued";
    makeAutoObservable(this);
  }

  setRequests(requests) {
    this._requests = requests;
  }
  setSelectedState(state) {
    this._selectedState = state;
  }

  get states() {
    return this._states;
  }
  get getRequests() {
    return this._requests;
  }
  get selectedState() {
    return this._selectedState;
  }
}
